### ISSUE TITLE
Создание архивной версии документа

### ISSUE THREAD

**Issue by SquakR** [devind-team/dcis#1190]
Необходимо создавать архивную версию документа после перевода статуса документа в «Требует доработки»

**Comment by SaltRedginald** [comment]
Добавить поле "архив" к статусу foreign key на период.
Архивировать период и всё, что к нему относится в функции класса AddStatusCheck: документ,  value, sheets, col_dimention, row_dimention, cell, merged_sell
Добавить функцию в таблицу add_status.
Добавить поле в фикстуру.
