### ISSUE TITLE
Реализовать раскраску при импорте и экспорте форм заполнения

### ISSUE THREAD

**Issue by Luferov** [devind-team/dcis#21]
Необходимо обеспечить поддержку цветов шрифта и фона при импорте Эксель файлов в систему, а также обеспечить сохранение при экспорте.

**Comment by alekcahdp** [comment]
Добавлены цвета для шрифтов, заливки ячеек, добавлены границы и их цвета.

В связи с тем что у библиотеки openpyxl свои стили для границ, а в разметке совсем другие, некоторые нераспространненые стили оформления границ не проработаны на фронте, что в дальнейшем будет исправлено.

Также если оформляется цвет границы, то стиль границы изменен на solid, так как в разметке border-collapse не позволяет рендерить цвет верхней и левой границы ячейки
