### ISSUE TITLE
Проблемы с рендером документа

### ISSUE THREAD

**Issue by Luferov** [devind-team/dcis#219]
Когда я загружаю вот этот простой файл
[Тест с подстроками.xlsx](https://github.com/devind-team/dcis/files/8550441/default.xlsx)

Возникает следующая проблема:
![image](https://user-images.githubusercontent.com/26242554/164994759-d930c35a-a590-4594-8bc2-35dc36b1de15.png)

![image](https://user-images.githubusercontent.com/26242554/164994833-edb3d6fd-ffaa-41de-853a-4dbb89332b5c.png)

Временное решение, не знаю на сколько оно подходит:
![image](https://user-images.githubusercontent.com/26242554/164994809-f8b4e99a-03f3-4e5a-a3c2-c529b5b36d90.png)

**Comment by Luferov** [comment]
И насколько это утверждение верно с колонками?

**Comment by SquakR** [comment]
Хм, странно как оно работало тогда. С boundaryColumnCells по идее такое не нужно, там можно пропускать строки, они всегда есть.
