### ISSUE TITLE
Проблема с загрузкой xlsx документа

### ISSUE THREAD

**Issue by Luferov** [devind-team/dcis#40]
При загрузке прикрепленного документа возникает ошибка:
На клиенте:
![image](https://user-images.githubusercontent.com/26242554/158796825-6eb8422c-d22a-4473-8383-4408b6dc21e0.png)

На сервере:
![image](https://user-images.githubusercontent.com/26242554/158796925-1f59716b-67fe-45a8-bb1f-0b139b666efb.png)

Загружаемый файл прикрепляю.
[2_5267472553240172562.xlsx](https://github.com/devind-team/dcis/files/8284167/2_5267472553240172562.xlsx)

**Comment by Luferov** [comment]
А теперь попробуй вот этот файл. Выдает ошибку, как прежде:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/26242554/158900046-c01186a9-aa06-4e4f-8553-596f7e90d542.png">


[Тестовый проект сборов.xlsx](https://github.com/devind-team/dcis/files/8292784/default.xlsx)

**Comment by Luferov** [comment]
Работает ли загрузка этого файла?
Создал в ubuntu с помощью libreoffice
[Тестовый файл.xlsx](https://github.com/devind-team/dcis/files/8309987/default.xlsx)
.

**Comment by alekcahdp** [comment]
Теперь думаю всё нормально работает
