### ISSUE TITLE
Добавить выбор дивизиона при создании документа

### ISSUE THREAD

**Issue by Luferov** [devind-team/dcis#484]
Если множественное заполнение и у пользователя не стоит явный дивизион, требуется указывать дивизион при выборе.

![image](https://user-images.githubusercontent.com/26242554/177870645-f3345945-3bd4-4933-a92f-f1262b6ba3a1.png)

**Comment by Luferov** [comment]
если есть привилегия **add_document** - разрешить выбор из всего списка

**Comment by SquakR** [comment]
Я тут подумал, и по идее нужно всегда позволять выбирать из списка. А список - добавленные дивизионы периода. Если выбирать из дивизионов пользователя, то дивизион может быть не добавлен к периоду, и тогда его нужно добавлять при добавлении документа, что неявное поведение. Лучше пусть у кого есть право добавлять дивизионы добавит дивизионы, а у того у кого есть право добавлять документ выберет из этого списка, даже если он не состоит в этом дивизионе.

**Comment by SquakR** [comment]
На пересечении дивизионов пользователя и периода, если есть право создать документ, но нет локального разрешения add_document, наверное это имелось в виду. А если разрешение есть, то из всех дивизионов периода, но мне кажется - это слишком сложно

**Comment by SquakR** [comment]
См. #574
