### ISSUE TITLE
Добавить стили границ на клиенте

### ISSUE THREAD

**Issue by alekcahdp** [devind-team/dcis#53]
В связи с тем, что стили на сервере не совпадают со стилями разметки, необходимо задать дополнительные стили. Также нужно добавить стиль диагонали на клиенте
![image](https://user-images.githubusercontent.com/86019934/159140076-399a21ae-0435-43b8-a052-e32f8dfe2bb6.png)
![image](https://user-images.githubusercontent.com/86019934/159140131-cfced306-2a59-4d78-8ed9-9867aaa6f172.png)

**Comment by Luferov** [comment]
Пока что не актуально.
