### ISSUE TITLE
Переработать профиль пользователя

### ISSUE THREAD

**Issue by SquakR** [devind-team/dcis#651]
Необходимо убрать регистрационные данные, т.к. они есть на портале.

![image](https://user-images.githubusercontent.com/66582102/183713915-c307e9f5-1121-4a34-a286-93f82705105d.png)

**Comment by Luferov** [comment]
@SquakR а вот и вопрос, что лучше, скрыть или удалить. Давайте удалим лишнее, гит помнит все
