### ISSUE TITLE
Отображение ошибок в формулах

### ISSUE THREAD

**Issue by SquakR** [devind-team/dcis#729]
Необходимо сделать понятное для пользователей отображение ошибок в формулах (таких как деление на 0). Возможно стоит сделать также, как сейчас сделано отображение ошибки типа "Циклическая ссылка".

**Comment by Luferov** [comment]
У меня была идея выделять границу вокруг ячейки красным цветом, а при наведении (hover) подчеркивать выводить tooltip о том, какая ошибка произошла
