### ISSUE TITLE
Подсветка строк и столбцов а зависимости от позиции курсора в ячейке

### ISSUE THREAD

**Issue by Luferov** [devind-team/dcis#74]
При наведении на ячейки необходимо сделать подсветку строк и столбцов для более удобной навигации.

Пример можно найти тут: https://codepen.io/dmjcomdem/pen/opVxZM

**Comment by SquakR** [comment]
Решено отказать от выделение при наведении в пользу выделение столбца и строки для выделенных ячеек.
![image](https://user-images.githubusercontent.com/66582102/163503904-a33a0d6a-e836-4a8c-bbec-881535409241.png)
