### ISSUE TITLE
Добавить раздел для просмотра методического обеспечения

### ISSUE THREAD

**Issue by Luferov** [devind-team/dcis#828]
Методические рекомендации, как в системе Зверева (они есть в базе, просто нужно нарисовать) на клиенте. Возможно, необходимо переделать под relay.

**Comment by SaltRedginald** [comment]
Создать раздел методических рекомендаций. Обеспечить куратора и администратора возможностью добавить файл, удалить файл. У представителей учреждений должна быть возможность просмотра списка файлов и скачивание.
