### ISSUE TITLE
Переработка и загрузка

### ISSUE THREAD

**Issue by SaltRedginald** [devind-team/dcis#961]
Задача: Реализовать в БД таблицы для справочника кураторских групп, привязки учреждений к кургруппам, привязки пользователей к кургруппам (кураторов). Загрузить туда сведения из файла:
https://www.dropbox.com/s/wjxhjzj9b3t0qkm/2022_09_13_kurators_orgs_users.xlsx?dl=0
Вариант решения: Раздел группы и пользователи нужно объекдинить в один и назвать его куратора. В этом разделее. Создавать группы кураторов и выполнять следующие настройки:
1 - назначать на краторов привилегии, а также в отдельности на пользователей (реализовано)
2 - добавлять пользователей в кураторские группы
3 - привязывать группы кураторов к дивизионам и распространять действие привилегий только на разрешенные дивизионы.

**Comment by MiloslavskiySergey** [comment]
Эта задача выполнялась на ветке кураторы
